* Arc
Arc (from ARChive) is a program for getting things out of your way
that you don't want to delete. It takes files that you specify on the
command line and moves them under the archive-dir, mirroring their
original location in your filesystem. Ex:

My archive-dir is =/home/me/.archives/= and I'm working in =/home/me/projects/=
I run:
#+BEGIN_SRC bash
$ arc project1.py sometempfile
#+END_SRC

Those two files will be moved to:

#+BEGIN_SRC bash
/home/me/.archives/home/me/projects/project1.py
/home/me/.archives/home/me/projects/sometempfile
#+END_SRC

#+BEGIN_SRC
Usage:
  arc <file>... [options]

Options:
  \-a DIR,  --archive-dir DIR   Specifies the directory to which files will be archived. [default: ~/.archives]
#+END_SRC

* Copyright and License Information

 Copyright 2013 Matthew Jaffee

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
